name: biodetect
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.7.5

  # UI & Images
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Storage & Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Auth
  google_sign_in: ^6.1.5

  # Maps - Mapbox
  image: ^4.0.17
  mapbox_maps_flutter: ^2.0.0

  # Conexión a servidor de la IA
  http: ^0.13.5

  # PDF y compartir
  intl: ^0.19.0
  pdf: ^3.10.4
  printing: ^5.12.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_logo_biodetect.png
    - assets/ic_google.png
    - assets/map_markers/
    - assets/badge_icons/
