name: biodetect
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Auth - VERIFICAR VERSIÓN
  google_sign_in: ^6.1.5

  # UI & Images
  cached_network_image: ^3.3.1
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8

  # Location
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Storage & Database
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  path: ^1.9.0

  # Maps - Mapbox
  image: ^4.2.0
  mapbox_maps_flutter: ^2.0.0

  # Conexión a servidor de la IA
  http: ^1.2.2

  # PDF Y COMPARTIR CON VERSIONES COMPATIBLES
  intl: ^0.20.2
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_logo_biodetect.png
    - assets/ic_google.png
    - assets/map_markers/
    - assets/badge_icons/
